name: famtask
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0' # Broaden SDK range for compatibility

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  uuid: ^4.5.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.19.0
  web: ^1.0.0
  characters: ^1.3.0
  material_color_utilities: ^0.11.1
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.4.4
  json_serializable: ^6.8.0
  leak_tracker: ^10.0.9
  leak_tracker_testing: ^3.0.1
  test_api: ^0.7.3
  vector_math: ^2.1.4
  vm_service: ^15.0.0 # Updated to resolve conflict

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/apple_logo.png
    - assets/images/google_logo.png