// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmSAPZ2njXeC5T8RIMn4JevrzfeZobs3c',
    appId: '1:229019082339:web:662c1819e518f888046256',
    messagingSenderId: '229019082339',
    projectId: 'famtask-2d42e',
    authDomain: 'famtask-2d42e.firebaseapp.com',
    storageBucket: 'famtask-2d42e.firebasestorage.app',
    measurementId: 'G-PBQ1CRFQ12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiTx1Uh8kX2bSSI958f-KZ0bErNwkSRqE',
    appId: '1:229019082339:android:a9d156067dda6c81046256',
    messagingSenderId: '229019082339',
    projectId: 'famtask-2d42e',
    storageBucket: 'famtask-2d42e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArr4yDbt4OsCWZccxZMJ7ZG03_OSCmnXs',
    appId: '1:229019082339:ios:637566d4e82c9b89046256',
    messagingSenderId: '229019082339',
    projectId: 'famtask-2d42e',
    storageBucket: 'famtask-2d42e.firebasestorage.app',
    iosBundleId: 'com.example.famtask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArr4yDbt4OsCWZccxZMJ7ZG03_OSCmnXs',
    appId: '1:229019082339:ios:637566d4e82c9b89046256',
    messagingSenderId: '229019082339',
    projectId: 'famtask-2d42e',
    storageBucket: 'famtask-2d42e.firebasestorage.app',
    iosBundleId: 'com.example.famtask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmSAPZ2njXeC5T8RIMn4JevrzfeZobs3c',
    appId: '1:229019082339:web:5b1daa801e2e4998046256',
    messagingSenderId: '229019082339',
    projectId: 'famtask-2d42e',
    authDomain: 'famtask-2d42e.firebaseapp.com',
    storageBucket: 'famtask-2d42e.firebasestorage.app',
    measurementId: 'G-Z2KMPKXH1P',
  );
}
